#ifndef COUCHDBENUMS_H
#define COUCHDBENUMS_H

enum CouchDBReplyStatus
{
    COUCHDB_SUCCESS,
    COUCHDB_ERROR,
    COUCHDB_AUTHERROR,
    COUCHDB_TIMEOUT
};

enum CouchDBOperation
{
    COUCHDB_CHECKINSTALLATION,
    COUCHDB_STARTSESSION,
    COUCHDB_ENDSESSION,
    COUCHDB_LISTDATABASES,
    COUCHDB_CREATEDATABASE,
    COUCHDB_DELETEDATABASE,
    COUCHDB_LISTDOCUMENTS,
    COUCHDB_RETRIEVEREVISION,
    COUCHDB_RETRIEVEDOCUMENT,
    COUCHDB_UPDATEDOCUMENT,
    COUCHDB_DELETEDOCUMENT,
    COUCHDB_UPLOADATTACHMENT,
    COUCHDB_DELETEATTACHMENT,
    COUCHDB_REPLICATEDATABASE
};

#endif // COUCHDBENUMS_H
